paths:
  data: './hada/datasets'
  ml_models: './hada/trained_models'
  algorithms_configs: './hada/config/algorithms'
  categorical_mappings: './hada/config/categorical_mappings'
  logic_rules: './hada/logic_rules_extracted'
  results: './results'
  ml_models_training_info: './hada/trained_models/info'
  logic_rules_extraction_info: './hada/logic_rules_extracted/info'
  storage_ws_url: 'http://localhost:5333'
  remote_address: 'http://172.28.0.2:5333'


rules_types:
  cart: 'CART'
  creepy: 'CReEPy'
  gridex: 'GridEx'
  gridrex: 'GridREx'


algorithms:
  anticipate: 'anticipate'
  contingency: 'contingency'
  convolution: 'convolution'
  correlation: 'correlation'
  fwt: 'fwt'
  saxpy: 'saxpy'
  toyalg: 'toyalg'


app:
  secret_key: ';u_QC&vzGaAR;&67vma[(4_cHZ;(F!;]dwjh&tJRBF;S(7aWYz/e=z!]^Fhk.K!@'